### PR TITLE
Disable shell integration

### LINKED ISSUE #21537: Che-Code auto-opened terminal doesn't work (for `main` branch)
### Describe the bug

The terminal widget that's opened automatically on Che-Code start is not connected to machine-exec.
image

Note, that the terminal opened manually (from the dropdown menu) works as expected:
image

### Che version

next (development version)

### Steps to reproduce

Start a workspace with Che-Code editor.

### Expected behavior

The auto-opened terminal should be ready to use.

### Runtime

OpenShift

### Screenshots

_No response_

### Installation method

OperatorHub

### Environment

Linux

### Eclipse Che Logs

```shell
In the editor container:

time="2022-07-07T19:13:47Z" level=error msg="Unable to initialize terminal. Cause: container with name Terminal was not found."
```
```


### Additional context

_No response_

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Disable the [extended shell integration](https://code.visualstudio.com/updates/v1_70#_shell-integration-enabled-by-default) feature as it breaks the machine-exec terminal.

fixes https://github.com/eclipse/che/issues/21537

#### How to test
Once the github-actions bot publishes the quay.io/che-incubator-pull-requests/che-code:pr-90-amd64 image (it should comment on the PR), run <che-host>#https://github.com/azatsarynnyy/java-spring-petclinic/tree/devfilev2.
Check that the terminal, opened on Che-Code start, works as expected.

### CODE REVIEW

File: code/src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts [hunk 1]
```diff
@@ -535,7 +535,7 @@ const terminalConfiguration: IConfigurationNode = {
 			restricted: true,
 			markdownDescription: localize('terminal.integrated.shellIntegration.enabled', "Determines whether or not shell integration is auto-injected to support features like enhanced command tracking and current working directory detection. \n\nShell integration works by injecting the shell with a startup script. The script gives VS Code insight into what is happening within the terminal.\n\nSupported shells:\n\n- Linux/macOS: bash, pwsh, zsh\n - Windows: pwsh\n\nThis setting applies only when terminals are created, so you will need to restart your terminals for it to take effect.\n\n Note that the script injection may not work if you have custom arguments defined in the terminal profile, a [complex bash `PROMPT_COMMAND`](https://code.visualstudio.com/docs/editor/integrated-terminal#_complex-bash-promptcommand), or other unsupported setup. To disable decorations, see {0}", '`#terminal.integrated.shellIntegrations.decorationsEnabled#`'),
 			type: 'boolean',
-			default: true
+			default: false // disabled, for machin-exec support
```
Comment (benoitf) [inline code/src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts]:
```suggestion
			default: false // disabled, for machine-exec support
```

**Review by benoitf — APPROVED** [review]
